s/echo/printf/ -- and some extra juju to go with

diff --git a/aurcomm b/aurcomm
--- a/aurcomm
+++ b/aurcomm
@@ -37,7 +37,7 @@ getpkgID() {
 
 if ! (( $# )); then
   if [[ ! -f PKGBUILD ]]; then 
-    echo "error: no PKGBUILD found and no arg provided"
+    printf "error: no PKGBUILD found and no arg provided\n"
     exit 1
   fi
   eval $(grep '^pkgname=' PKGBUILD)
@@ -46,7 +46,7 @@ fi
 pkgname=${1:-$pkgname}
 
 pkgID=$(getpkgID $pkgname)
-[[ $pkgID ]] || { echo "error: package \`$pkgname' not found"; exit 1; }
+[[ $pkgID ]] || { printf "error: package \`%s' not found" "$pkgname"; exit 1; }
 
 curl -s "$AURURL/packages.php?ID=$pkgID$showall" | commfilter
 
diff --git a/git-retrotag b/git-retrotag
--- a/git-retrotag
+++ b/git-retrotag
@@ -87,8 +87,8 @@ review_candidates() {
 
 ask_abort() {
   read -N1 -p "Satisfied? Continue with tagging? (y/N) " reply
-  echo
-  [[ ! "$reply" =~ [Yy] ]] && { echo "Aborting..."; exit 1; }
+  printf "\n"
+  [[ ! "$reply" =~ [Yy] ]] && { printf "Aborting...\n"; exit 1; }
 }
 
 tag_commits() {
@@ -118,10 +118,10 @@ tag_commits() {
   done
 
   if (( count > 0 )); then
-    echo
+    printf "\n" 
     msg "Finished: Added $count new tags. Use \`git push --tags\` to update the remote."
   else
-    echo
+    printf "\n" 
     msg "Finished: No new tags were added."
   fi
 }
diff --git a/hglink b/hglink
--- a/hglink
+++ b/hglink
@@ -13,11 +13,11 @@ get_hgroot() {
   while [[ $curpath && ! -d $curpath/.hg ]]; do
     curpath=${curpath%/*}
   done
-  [[ $curpath ]] && echo "$curpath"
+  [[ $curpath ]] && printf "%s\n" "$curpath"
 }
 
 usage() {
- echo "Usage: ${0##*/} [ -l linenum ] [ -b ] <file> [ hash ]"
+ printf "Usage: %s [ -l linenum ] [ -b ] <file> [ hash ]" "${0##*/}"
 } >&2
 
 while getopts ":bhl:" opt; do
@@ -25,8 +25,8 @@ while getopts ":bhl:" opt; do
     b) OPENINBROWSER=1 ;;
     h) usage; exit 1 ;;
     l) LINE=$OPTARG ;;
-    \:) echo "Argument required for -$OPTARG" ;;
-    \?) echo "error: bad arg, no bisuit" ;;
+    \:) printf "Argument required for -%s\n" "$OPTARG" ;;
+    \?) printf "error: bad arg, no bisuit\n" ;;
   esac >&2
 done
 shift $(( OPTIND - 1 ))
@@ -35,7 +35,7 @@ shift $(( OPTIND - 1 ))
 
 fullpath=$(readlink -m "$1")
 hg_root=$(get_hgroot "$fullpath")
-[[ -z $hg_root ]] && { echo "error: '$1' is not in an hg repo"; exit 1; }
+[[ -z $hg_root ]] && { printf "error: '%s' is not in an hg repo\n" "$1"; exit 1; }
 
 # we need to operate from within the hg repo. if we're not in it, go there
 [[ ${PWD#$hg_root} = $PWD ]] && cd $hg_root
@@ -53,7 +53,7 @@ rev=${2:-$(hg log -r $remotetip | awk -F: 'NR == 1 { print $3 }')}
 # relative path from repo root to file
 relpath=${fullpath#$hg_root/}
 if [[ -z $relpath ]]; then
-  echo "error: failed to determine path to $1. tell dave he sucks at bash"
+  printf "error: failed to determine path to %s. tell dave he sucks at bash\n" "$1"
   exit 1
 fi
 
@@ -64,11 +64,11 @@ urlout="${remotepath}/file/$rev/$relpath${LINE:+#l$LINE}"
 if type -P curl >/dev/null; then
   # hgweb kindly responds with a 404 on an invalid link -- so let's validate!
   if ! curl -sf "$urlout" >/dev/null; then
-    echo "error: failed to create a valid link to '$1'. check your repo and filepath"
+    printf "error: failed to create a valid link to '%s'. check your repo and filepath\n" "$1"
     exit 1
   fi
 fi
 
-# echo or open in browser
-(( OPENINBROWSER )) && ${BROWSER:-chromium} "$urlout" || echo "$urlout"
+# print or open in browser
+(( OPENINBROWSER )) && ${BROWSER:-chromium} "$urlout" || printf "%s\n" "$urlout"
 
diff --git a/sabs b/sabs
--- a/sabs
+++ b/sabs
@@ -17,23 +17,23 @@ getrepo() {
   fi
 }
 
-[[ -z $1 ]] && { echo "Usage: ${0##*/} targets..."; exit 1; }
+[[ -z $1 ]] && { printf "Usage: %s targets...\n" "${0##*/}"; exit 1; }
 
 for pkg; do
   # read only the first, repo is only of mild importance
   read repo _ < <(getrepo $pkg)
-  [[ -z $repo ]] && { echo "error: package \`$pkg' not found"; continue; }
+  [[ -z $repo ]] && { printf "error: package \`%s' not found" "$pkg"; continue; }
 
   case $repo in
     @(community|multilib)*) repo=community ;;
     *) repo=packages ;;
   esac
 
-  [[ -d $pkg ]] && { echo  "error: directory \`$pkg' already exists"; continue; }
+  [[ -d $pkg ]] && { printf "error: directory \`%s' already exists" "$pkg"; continue; }
 
   svn export "$svnrepo/$repo/$pkg/trunk" $pkg >/dev/null &&
-    echo ":: checked out $pkg" ||
-    echo "error: failed to get package \`$pkg'"
+    printf ":: checked out %s\n" "$pkg" ||
+    printf "error: failed to get package \`%s'\n" "$pkg"
 
 done
 
diff --git a/walk b/walk
--- a/walk
+++ b/walk
@@ -21,7 +21,7 @@ get_pwd_contents() {
     [[ -d $f ]] && dir+=("$f") || nondir+=("$f")
   done
 
-  echo "${dir[@]}" "${nondir[@]}"
+  printf "%q\n" "${dir[@]}" "${nondir[@]}"
 }
 
 walk() {
@@ -31,8 +31,8 @@ walk() {
   (( indent += $IND_SZ ))
   pushd "$1" &>/dev/null
 
-  [[ $DIRS_FIRST ]] && dir_contents=$(get_pwd_contents) || dir_contents=(*)
-  for entry in $(get_pwd_contents); do
+  [[ $DIRS_FIRST ]] && dir_contents=($(get_pwd_contents)) || dir_contents=(*)
+  for entry in "${dir_contents[@]}"; do
     [[ -d $entry && ! -L $entry ]] && walk "$entry" || printentry "$entry"
   done
 
@@ -51,7 +51,7 @@ indent=0
 (( $# == 0 )) && DIRS=(.) || DIRS=($@)
 
 for basedir in "${DIRS[@]}"; do
-  cd "$basedir" 2>/dev/null || { echo "Directory not found: '$basedir'" >&2; continue; }
+  cd "$basedir" 2>/dev/null || { printf "Directory not found: '%s'\n" "$basedir" >&2; continue; }
   walk "$basedir"
 done
 
