aurrpc: lose curl dep. needs more bash sockets

diff --git a/aurrpc b/aurrpc
--- a/aurrpc
+++ b/aurrpc
@@ -16,5 +16,30 @@ esac
 
 [[ $qtype = @(info|?(m)search) ]] || exit 2
 
-curl -Ls "http://aur.archlinux.org/rpc.php?type=$qtype&arg=$arg" | out
+# open connection
+exec 4<>/dev/tcp/aur.archlinux.org/80
+
+# send http request (avoid 1.1 so we don't have to handle a keep-alive)
+printf 'GET /rpc.php?type=%s&arg=%s HTTP/1.1\r
+User-Agent: bashium 0.1\r
+Host: aur.archlinux.org\r
+Accept: */*\r
+Accept-Encoding: deflate, gzip\r
+\r
+' "$qtype" "$arg" >&4
+
+# read http response code
+read -r -u 4 _ resp _
+if [[ $resp ]] && (( resp >= 300 )); then
+  echo "error: server responded with HTTP $resp"
+  exit 1
+fi
+
+# read response until the end of the headers
+while read -r -u 4 body; do
+  [[ $body = $'\r' ]] && break
+done
+
+# gunzip the remainder of the FD
+gzip -d <&4 | out
 
