aurrpc: add warn/info/die/error functions

diff --git a/aurrpc b/aurrpc
--- a/aurrpc
+++ b/aurrpc
@@ -26,6 +26,27 @@ usage() {
   exit 1
 }
 
+die() {
+  error "$@"
+  exit 1
+}
+
+error() {
+  local mesg=$1; shift
+  printf "\033[1;31m::\033[0m $mesg\n" "$@"
+}
+
+warn() {
+  local mesg=$1; shift
+  printf "\033[1;33m::\033[0m $mesg\n" "$@"
+}
+
+info() {
+  local mesg=$1; shift
+  printf "\033[1;34m::\033[0m \033[1m$mesg\033[0m\n" "$@"
+}
+
+
 # content handlers
 json() {
   type -P json_reformat >/dev/null && json_reformat || cat
@@ -34,9 +55,9 @@ json() {
 x-tgz() {
   tar xz
   if (( $? )); then 
-    printf 'error downloading %s\n' "$target"
+    error 'error downloading %s' "$target"
   else
-    printf '%s downloaded to %s\n' "$target" "$PWD"
+    info '%s downloaded to %s' "$target" "$PWD"
   fi
 }
 
@@ -54,7 +75,7 @@ deflate() {
 # connect handler
 connect() {
   { exec 4<>/dev/tcp/$hostname/$port; } 2>/dev/null
-  (( $? )) && { printf 'error: failed to connect to %s:%s\n' "$hostname" "$port"; exit 1; }
+  (( $? )) && { die 'error: failed to connect to %s:%s\n' "$hostname" "$port"; }
 }
 
 shutdown() {
@@ -80,11 +101,9 @@ read_response_code() {
   read -r -u 4 _ resp _
   if [[ $resp ]]; then
     if (( resp == 404 )); then
-      echo "error: package $target not found"
-      exit 1
+      die "package \`%s' not found" "$target"
     elif (( resp >= 300 )); then
-      echo "error: server responded with HTTP $resp"
-      exit 1
+      die "server responded with HTTP %d" "$resp"
     fi
     # assume HTTP 200 (eww)
   fi
@@ -102,12 +121,12 @@ read_response_headers() {
   content_type=${content_type##*/} # trim 'application/'
 
   if [[ $(type -t $content_type) != @(function|file) ]]; then
-    printf 'error: unknown/unhandled content type: %s\n' "$content_type"
+    die 'unknown/unhandled content type: %s\n' "$content_type"
     exit 1
   fi
 
   if [[ $(type -t $content_encoding) != @(function|file) ]]; then
-    printf 'error: unknown/unhandled encoding type: %s\n' "$content_encoding"
+    die 'unknown/unhandled encoding type: %s\n' "$content_encoding"
     exit 1
   fi
 }
@@ -144,7 +163,7 @@ while getopts ':dhims' opt; do
     i) uri=$fmt_rpcpath; rtype=rpc; qtype=info ;;
     m) uri=$fmt_rpcpath; rtype=rpc; qtype=msearch ;;
     s) uri=$fmt_rpcpath; rtype=rpc; qtype=search ;;
-    ?) printf '%s : invalid option -- '\''%s'\'' \n' "${0##*/}" "$OPTARG"
+    ?) die '%s: invalid option -- '\''%s'\' "${0##*/}" "$OPTARG"
        exit 1 ;;
     *) usage ;;
   esac
