csv2html: allow merging of multiple CSVs into single html

diff --git a/csv2html b/csv2html
--- a/csv2html
+++ b/csv2html
@@ -3,41 +3,53 @@
 NUMFIELDS=0
 OUT=()
 
-# use a common FD based on where we read from
-# TODO: Currently ignores args after the first. Allow reading from multiple files?
-case $# in
-  0) exec 6<&0 ;;
-  *) exec 6< "$1" ;;
-esac
+to_html() {
+  local LC=0 # line counter in case of error
 
+  while IFS=',' read -r -a items; do
+    (( ++LC ))
+    OUT+=("\t<tr>\n") # start row
+
+    # skip blank lines, but not lines with empty fields
+    (( ${#items[@]} == 0 )) && continue
+
+    # assert: all rows are same number of columns
+    (( NUMFIELDS == 0 )) && NUMFIELDS=${#items[@]}
+    if (( NUMFIELDS != ${#items[@]} )); then
+      echo "error: Malformed CSV ($file: line $LC). Expected $NUMFIELDS fields, found ${#items[@]}." >&2
+      exit 1
+    fi
+
+    # output each column, stripping NULL tokens
+    for item in "${items[@]}"; do
+      OUT+=("\t\t<td>${item/==NULL==/}</td>\n")
+    done
+
+    OUT+=("\t</tr>\n") # end row
+
+  # replace blank fields with a dummy value so read doesn't skip them
+  done < <(sed 's/^,/==NULL==,/; s/,,/,==NULL==,/g; s/,$/,==NULL==/' <&6)
+}
+
+OUT+=("<table>\n") # header
+
+# use a new FD to unify where to read from
+if (( $# == 0 )); then
+  exec 6<&0
+  to_html
+else
+  for file; do
+    exec 6< "$file"
+    to_html
+    exec 6<&-
+  done
+fi
+
+# and ensure its closed
 trap 'exec 6<&-' 0
 
-LC=0 # line counter in case of error
-OUT+=("<table>\n")
-while IFS=',' read -r -a items; do
-  (( ++LC ))
-  OUT+=("\t<tr>\n") # start row
-
-  # skip blank lines, but not lines with empty fields
-  (( ${#items[@]} == 0 )) && continue
-
-  # assert: all rows are same number of columns
-  (( NUMFIELDS == 0 )) && NUMFIELDS=${#items[@]}
-  if (( NUMFIELDS != ${#items[@]} )); then
-    echo "error: Malformed CSV (line $LC). Expected $NUMFIELDS fields, found ${#items[@]}." >&2
-    exit 1
-  fi
-
-  # output each column, stripping NULL tokens
-  for item in "${items[@]}"; do
-    OUT+=("\t\t<td>${item/==NULL==/}</td>\n")
-  done
-
-  OUT+=("\t</tr>\n") # end row
-
-# replace blank fields with a dummy value so read doesn't skip them
-done < <(sed 's/^,/==NULL==,/; s/,,/,==NULL==,/g; s/,$/,==NULL==/' <&6)
-OUT+=("</table>\n")
+OUT+=("</table>\n") # footer
 
 echo -e "${OUT[@]}"
+
 
