git-all: simplify script. assume you're using a git command

diff --git a/git-all b/git-all
--- a/git-all
+++ b/git-all
@@ -4,7 +4,6 @@
 #   -S    Show repos which have uncommitted changes. If this"
 #          option is specified, all other options are ignored."
 #
-#   -f    suppress prompting before a custom command is run"
 #   -v    print error output in job summary for failed jobs"
 #
 # Actions will be performed on $REPOHOME, which defaults to $HOME"
@@ -12,7 +11,6 @@
 #
 
 REPOHOME=${REPOHOME:-$HOME}
-FORCE=0
 VERBOSE=0
 
 count=0
@@ -43,33 +41,15 @@ repofail() {
   printf " \033[1;0m\033[0;34m[\033[1;31mFAIL\033[0;34m] \033[0;36m %s\033[0m\n" "$1" >&2
 }
 
-verify_execute() {
-  msg "Command to be executed: $*"
-  echo -ne "\033[1;33m::\033[0m"
-  read -N1 -p " Are you sure you want to do this? [y/N] " reply
-  echo
-
-  [[ ! "$reply" =~ [Yy] ]] && die "Operation aborted" && exit 1
-}
-
-validate_command() {
-  type -P $1 &> /dev/null || {
-    die "Invalid command: '$1'";
-    exit 1;
-  }
-}
-
 do_all_action() {
   IFS=$'\n' read -r -d $'\0' -a repos < <(find "$REPOHOME" -type d -name '.git' -exec readlink -f {} \;)
 
   for repo in "${repos[@]}"; do
     (( ++count ))
     local repo=${repo%.git}
+
     cd "$repo"
-
-    output[$repo]=$("$@" 2>&1) &&
-      pass=(${pass[@]} "$repo") || fail=(${fail[@]} "$repo")
-
+    output[$repo]=$(git "$@" 2>&1) && pass=(${pass[@]} "$repo") || fail=(${fail[@]} "$repo")
   done
 }
 
@@ -85,7 +65,7 @@ stat_repos() {
 
 job_summary() {
   echo
-  msg "Job Summary For $count Repos: $*"
+  msg "Job Summary For $count Repos: git $*"
 
   if [[ ${#fail[@]} -eq 0 ]]; then
     msg2 "No errors were reported"
@@ -106,31 +86,21 @@ job_summary() {
 # sanity check
 [[ ! -r "$REPOHOME" ]] && die "Invalid \$REPOHOME: $REPOHOME" exit 1
 
-while getopts :Sfv flag; do
+#while getopts :Sfv flag; do
+while getopts :Sv flag; do
   case $flag in
-    S) stat_repos
-       exit 0
-      ;;
-    f) FORCE=1
-      ;;
-    v) VERBOSE=1
-      ;;
-    \?) die "invalid option -- '$OPTARG'"
-      ;;
+    S) stat_repos; exit 0 ;;
+    v) VERBOSE=1 ;;
+    \?) die "invalid option -- '$OPTARG'" ;;
   esac >&2
 done
 
 shift $(( OPTIND-1 ))
 
 # check command line usage
-if [[ -z $1 ]]; then
-  sed -n '2,/^$/s/^# \?//p' "$0"
-  exit 1
-fi
+[[ $1 ]] || { sed -n '2,/^$/s/^# \?//p' "$0"; exit 1; }
 
 # main loop
-(( FORCE )) || verify_execute "$*"
-validate_command "$1"
 do_all_action "$@"
 job_summary "$@"
 
