git-all: refactor for great success
* change verbose option -- if specified, errors will be printed with the
  job summary, not during the execution
* change repo{pass,fail} to put status tag on the left. this means we
  don't need to worry about the length of the directory
* remove cruft from verify_execute
* simplify do_all_action logic inside for loop
* add a catchall in option parser for bad options as opposed to a non
  option causing us to break parsing and execute

diff --git a/git-all b/git-all
--- a/git-all
+++ b/git-all
@@ -10,14 +10,15 @@ declare -a pass
 declare -A output
 
 usage() {
+  echo
   echo "Usage: ${0##*/} [options] [command]"
   echo
   echo "   -S, --stat       Show repos which have uncommitted changes. If this"
   echo "                     option is specified, all other options are ignored."
   echo
   echo "   -f, --force      suppress prompting before a custom command is run"
-  echo "   -v, --verbose    be verbose. show output for each repo"
   echo "   -h, --help       print this help message"
+  echo "   -v, --verbose    print error output in job summary for failed jobs"
   echo
   echo " Actions will be performed on \$REPOHOME, which defaults to \$HOME"
   echo " if not specified."
@@ -37,26 +38,20 @@ msg2() {
 }
 
 repopass() {
-  printf "\033[0;36m %-60s \033[1;0m\033[0;34m[\033[1;37mPASS\033[0;34m]\033[0m\n" "$1"
+  printf "\033[1;0m\033[0;34m[\033[1;37mPASS\033[0;34m] \033[0;36m %s\033[0m\n" "$1"
 }
 
 repofail() {
-  printf "\033[0;36m %-60s \033[1;0m\033[0;34m[\033[1;31mFAIL\033[0;34m]\033[0m\n" "$1"
+  printf "\033[1;0m\033[0;34m[\033[1;31mFAIL\033[0;34m] \033[0;36m %s\033[0m\n" "$1"
 }
 
 verify_execute() {
-  if [[ $1 = "-f" ]]; then
-    shift
-  elif [[ $1 = "-v" ]]; then
-    VERBOSE=1
-    shift
-  else
-    msg "Command to be executed: $*"
-    read -N1 -p " Are you sure you want to do this? [y/N] " reply
-    echo;echo;
+  msg "Command to be executed: $*"
+  echo -ne "\033[1;33m::\033[0m"
+  read -N1 -p " Are you sure you want to do this? [y/N] " reply
+  echo;echo;
 
-    [[ ! "$reply" =~ [Yy] ]] && exit 1
-  fi
+  [[ ! "$reply" =~ [Yy] ]] && exit 1
 }
 
 validate_command() {
@@ -74,12 +69,9 @@ do_all_action() {
     repo=${repo%/.git}
     cd "$repo"
 
-    { if (( VERBOSE )); then
-        msg2 "In '$repo'";
-        output[$repo]=$("$@" 2>&1);
-      else
-        { output[$repo]=$("$@" 2>&1); } > /dev/null
-    fi; } && pass=(${pass[@]} "$repo") || fail=(${fail[@]} "$repo")
+    output[$repo]=$("$@" 2>&1) &&
+      pass=(${pass[@]} "$repo") ||
+      fail=(${fail[@]} "$repo")
 
   done
 }
@@ -102,9 +94,8 @@ job_summary() {
   else
     for repo in "${fail[@]}"; do
       repofail "$repo"
-      sed 's/^/   /' <<< "${output[$repo]}" && echo
+      (( VERBOSE )) && sed 's/^/   /' <<< "${output[$repo]}" && echo
     done
-  echo
   fi
   echo
 
@@ -124,13 +115,16 @@ while (( $# != 0 )); do
     -h|--help)
       usage
       ;;
-    -v|--verbose)
-      VERBOSE=1
-      ;;
     -f|--force)
       FORCE=1
       ;;
-    *) break ;;
+    -v|--verbose)
+      VERBOSE=1
+      ;;
+    (-*) usage
+      ;;
+    *) break;
+      ;;
   esac
   shift
 done
