sabs: more cleanup

diff --git a/sabs b/sabs
--- a/sabs
+++ b/sabs
@@ -5,11 +5,13 @@
 # requires: expac
 #
 
+shopt -s extglob
+
 svnrepo="svn://svn.archlinux.org"
 
 fetchclean() {
   local repo=$1 pkg=$2
-  svn export $(printf "$svnrepo/%s/%s" $repo $pkg) >/dev/null || return 1
+  svn export "$svnrepo/$repo/$pkg" >/dev/null || return 1
 
   pushd $pkg >/dev/null || return 1
   mv trunk/* .
@@ -17,8 +19,11 @@ fetchclean() {
   popd >/dev/null 
 }
 
+[[ -z $1 ]] && { echo "Usage: ${0##*/} targets..."; exit 1; }
+
 for pkg; do
-  read repo _ < <(expac -S %r $pkg)
+  # read only the first, repo is only of mild importance
+  read repo _ < <(expac -S '%r' $pkg)
   [[ -z $repo ]] && { echo "error: package \`$pkg' not found"; continue; }
 
   case $repo in
@@ -28,7 +33,9 @@ for pkg; do
 
   [[ -d $pkg ]] && { echo  "error: directory \`$pkg' already exists"; continue; }
 
-  fetchclean $repo $pkg || echo "error: failed to get package \`$pkg'"
-  echo ":: checked out $pkg"
+  fetchclean $repo $pkg &&
+    echo ":: checked out $pkg" ||
+    echo "error: failed to get package \`$pkg'"
+
 done
 
