Use fast fail logic instead of putting the execution in an else clause

diff --git a/simplentp b/simplentp
--- a/simplentp
+++ b/simplentp
@@ -1,10 +1,11 @@
 #!/bin/bash
 
-if [[ $UID -eq 0 ]]; then
-    echo "Setting hwclock to localtime from time.nist.gov..."
-    hwclock --set --date="$(cat < /dev/tcp/time.nist.gov/13 | awk '{print $2,$3}') UTC"
-    echo "Sync'ing hwclock to system..."
-    hwclock -s
-else
-    echo "Must be root to execute this!" >&2
+if [[ $UID -ne 0 ]]; then
+  echo "Error: Must be root!" >&2
+  exit 1
 fi
+
+echo "Setting hwclock to localtime from time.nist.gov..."
+hwclock --set --date="$(cat < /dev/tcp/time.nist.gov/13 | awk '{print $2,$3}') UTC"
+echo "Sync'ing hwclock to system..."
+hwclock -s
