sortwp: split logic into more digestable chunks

diff --git a/sortwp b/sortwp
--- a/sortwp
+++ b/sortwp
@@ -1,9 +1,11 @@
 #!/bin/bash
 
+type -P identify >/dev/null || { echo "identify not found -- missing imagemagick?"; exit 1 }
+
 wallpaper_root="$HOME/pic/wallpaper"
 
-find . -maxdepth 1 -type f | while read pic; do
-    dim=($(identify $pic | sed -n 's/.* \([0-9]\{3,4\}\)x\([0-9]\{3,4\}\) .*/\1 \2/p'))
+while read pic; do
+    read -r -a dim <(identify $pic | sed -n 's/.* \([0-9]\{3,4\}\)x\([0-9]\{3,4\}\) .*/\1 \2/p')
 
     case "$(echo "scale=3;${dim[0]} / ${dim[1]}" | bc)" in
         "1.777") ratio="16:9" ;;
@@ -20,5 +22,5 @@ find . -maxdepth 1 -type f | while read pic; do
 
     mv -v "$pic" "$wallpaper_root/$ratio/$prefix$(basename $pic)"
     unset prefix
-done
+done < <(find . -maxdepth 1 -type f)
 
